### ISSUE TITLE
Upload the powerpoint slide deck we had for the demo

### ISSUE THREAD

**Issue by benmatselby** [benmatselby/freeyourmindhackathon#1]
Hey @altis @Zuzeek @akc321 @ryan-farrell @JadeKneen @NubuTheKing 

Unsure which one of you has the presentation from the demo, but could one of you upload it to this repo please. It would be nice to have all of this in one place for posterity :)

Lovely working with you all yesterday.

**Comment by JadeKneen** [comment]
I have it on my laptop at Code Nation so I'll upload it on Monday 😊
________________________________

**Comment by benmatselby** [comment]
Fantastic. Thanks Jade, appreciate it 😁

**Comment by JadeKneen** [comment]
Uploaded the slides

**Comment by benmatselby** [comment]
Excellent, thank you Jade, appreciate it :)
